/**
 * One-off asset optimiser (run manually, NOT part of the build).
 *
 *   node scripts/optimize-images.mjs
 *
 * For every raster image under public/assets/images/ (except og/):
 *   1. resize so the longest side is <= MAX_EDGE (keeps source files sane),
 *   2. recompress the original in place (mozjpeg q80 / palette png),
 *   3. emit .webp + .avif siblings next to it (served via <picture>),
 *   4. record which modern formats were kept in src/data/image-manifest.ts
 *      (consumed by the <Picture> helper to emit only the <source>s that exist).
 *
 * Re-running is safe but lossy (it recompresses already-compressed files), so
 * run it once per batch of new images, then commit the result.
 */
import { readdir, readFile, writeFile, stat, unlink } from 'node:fs/promises';
import { join, relative, extname } from 'node:path';
import sharp from 'sharp';

const ROOT = 'public/assets/images';
const SKIP_DIRS = new Set(['og']);
const MAX_EDGE = 2000;
const JPEG_Q = 80;
const WEBP_Q = 78;
const AVIF_Q = 55;

/** Recursively list raster files, skipping SKIP_DIRS. */
async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (!SKIP_DIRS.has(entry.name)) out.push(...(await walk(full)));
    } else if (/\.(jpe?g|png)$/i.test(entry.name)) {
      out.push(full);
    }
  }
  return out;
}

/** "public/assets/images/venue/x.jpg" → "/assets/images/venue/x.jpg" (web path, used as manifest key). */
const webPath = (file) => '/' + relative('public', file).split(/[\\/]/).join('/');

/** Delete a file if it exists (used to drop stale siblings from a prior run). */
const rm = async (p) => {
  try {
    await unlink(p);
  } catch {
    /* not there — fine */
  }
};

async function run() {
  const files = (await walk(ROOT)).sort();
  const manifest = {};
  let before = 0;
  let after = 0;

  for (const file of files) {
    before += (await stat(file)).size;
    const isPng = extname(file).toLowerCase() === '.png';
    const input = await readFile(file);

    let pipeline = sharp(input).rotate();
    const meta = await pipeline.metadata();
    if (Math.max(meta.width ?? 0, meta.height ?? 0) > MAX_EDGE) {
      pipeline = pipeline.resize({ width: MAX_EDGE, height: MAX_EDGE, fit: 'inside', withoutEnlargement: true });
    }

    // Recompress the original (fallback) in place.
    const fallback = await (isPng
      ? pipeline.clone().png({ compressionLevel: 9, effort: 8, quality: JPEG_Q, palette: true })
      : pipeline.clone().jpeg({ quality: JPEG_Q, mozjpeg: true })
    ).toBuffer({ resolveWithObject: true });

    await writeFile(file, fallback.data);
    after += fallback.data.length;

    // Modern-format siblings — only kept when actually smaller than the fallback
    // (flat logos often compress worse as webp/avif than as palette PNG).
    const base = file.replace(/\.(jpe?g|png)$/i, '');
    const fb = fallback.data.length;
    const webp = await pipeline.clone().webp({ quality: WEBP_Q }).toBuffer();
    const avif = await pipeline.clone().avif({ quality: AVIF_Q }).toBuffer();
    const useWebp = webp.length < fb;
    const useAvif = avif.length < fb;
    // Write the sibling when it helps, otherwise remove any stale one from a prior run.
    if (useWebp) { await writeFile(`${base}.webp`, webp); after += webp.length; }
    else { await rm(`${base}.webp`); }
    if (useAvif) { await writeFile(`${base}.avif`, avif); after += avif.length; }
    else { await rm(`${base}.avif`); }

    manifest[webPath(file)] = {
      ...(useAvif ? { avif: true } : {}),
      ...(useWebp ? { webp: true } : {}),
    };

    console.log(
      `✓ ${webPath(file)}  ${(fb / 1024).toFixed(0)}k` +
        `${useWebp ? `  +webp ${(webp.length / 1024).toFixed(0)}k` : ''}` +
        `${useAvif ? `  +avif ${(avif.length / 1024).toFixed(0)}k` : ''}`
    );
  }

  const ts =
    `/**\n * AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.\n` +
    ` * Maps each image's web path to which modern formats exist, so <Picture>\n` +
    ` * emits only the <source>s whose sibling file was actually generated.\n */\n` +
    `export const imageManifest: Record<string, { avif?: boolean; webp?: boolean }> = ${JSON.stringify(manifest, null, 2)};\n`;
  await writeFile('src/data/image-manifest.ts', ts);

  console.log(`\n${files.length} images.  fallbacks: ${(before / 1e6).toFixed(1)}MB → ${(after / 1e6).toFixed(1)}MB (incl. webp+avif siblings).`);
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
