version: 2

updates:
  - package-ecosystem: npm
    directory: /startupweekendnantes.fr
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      root:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
