/**
 * AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
 * Maps each image's web path to its intrinsic size, so <Picture> can set
 * width/height and avoid layout shift (CLS).
 */
export const imageManifest: Record<string, { width: number; height: number; avif?: boolean; webp?: boolean }> = {
  "/assets/images/brand/logo-startup-weekend-nantes.png": {
    "width": 1024,
    "height": 330
  },
  "/assets/images/hero/hero-background.png": {
    "width": 1659,
    "height": 1361,
    "avif": true
  },
  "/assets/images/hero/hero-participants.png": {
    "width": 1440,
    "height": 1179
  },
  "/assets/images/intro/event-pitch-speaker.jpg": {
    "width": 2000,
    "height": 1331,
    "avif": true,
    "webp": true
  },
  "/assets/images/intro/intro-group-photo.jpg": {
    "width": 2000,
    "height": 1331,
    "avif": true,
    "webp": true
  },
  "/assets/images/intro/intro-team-brainstorming.jpg": {
    "width": 2000,
    "height": 1331,
    "avif": true,
    "webp": true
  },
  "/assets/images/intro/intro-tshirt-bad-ideas-good-stories.jpg": {
    "width": 2000,
    "height": 1331,
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/ana-pascaud.png": {
    "width": 1280,
    "height": 1707,
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/clara-garnier.png": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/florence-poyvre.png": {
    "width": 512,
    "height": 512,
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/gregory-thibord.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/guillaume-parthenay.png": {
    "width": 512,
    "height": 512,
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/louis-ammonique.png": {
    "width": 1080,
    "height": 1080,
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/robin-goutard.png": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/romain-perraut.png": {
    "width": 512,
    "height": 512,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/benjamin-communier.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/benjamin-guillet.png": {
    "width": 422,
    "height": 630,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/claire-bretton.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/eric-lebrette.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/florian-herveou.jpeg": {
    "width": 584,
    "height": 584,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/johan-ricaut.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/lucie-valette.jpeg": {
    "width": 461,
    "height": 461,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/mathilde-bermond.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/nicolas-laurent.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/pauline-corriou.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/samuel-berthe.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/simon-timssale.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/thomas-matthieu.jpeg": {
    "width": 452,
    "height": 452,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/vincent-roux.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/sponsors/sponsor-allovoisins.png": {
    "width": 1080,
    "height": 1080,
    "avif": true
  },
  "/assets/images/sponsors/sponsor-arzel.png": {
    "width": 768,
    "height": 458
  },
  "/assets/images/sponsors/sponsor-clever-cloud.png": {
    "width": 1310,
    "height": 1390
  },
  "/assets/images/sponsors/sponsor-crisp.png": {
    "width": 2000,
    "height": 499
  },
  "/assets/images/sponsors/sponsor-finalli.png": {
    "width": 2000,
    "height": 1600
  },
  "/assets/images/sponsors/sponsor-guest-suite.png": {
    "width": 1080,
    "height": 855
  },
  "/assets/images/sponsors/sponsor-icilundi.png": {
    "width": 512,
    "height": 312
  },
  "/assets/images/sponsors/sponsor-kiliogene.png": {
    "width": 1570,
    "height": 391
  },
  "/assets/images/sponsors/sponsor-nantes-metropole.png": {
    "width": 1080,
    "height": 1080
  },
  "/assets/images/sponsors/sponsor-pepite-pays-de-la-loire.png": {
    "width": 402,
    "height": 385
  },
  "/assets/images/sponsors/sponsor-reseau-entreprendre-atlantique.png": {
    "width": 1040,
    "height": 838
  },
  "/assets/images/venue/venue-palace-1.jpeg": {
    "width": 515,
    "height": 540,
    "avif": true,
    "webp": true
  },
  "/assets/images/venue/venue-palace-2.jpg": {
    "width": 2000,
    "height": 2000,
    "avif": true,
    "webp": true
  },
  "/assets/images/venue/venue-palace-3.jpeg": {
    "width": 864,
    "height": 540,
    "avif": true,
    "webp": true
  },
  "/assets/images/venue/venue-palace-4.jpg": {
    "width": 2000,
    "height": 1462,
    "avif": true,
    "webp": true
  },
  "/assets/images/venue/venue-palace-5.jpg": {
    "width": 2000,
    "height": 1483,
    "avif": true,
    "webp": true
  },
  "/assets/images/venue/venue-palace-panoramic.jpg": {
    "width": 2000,
    "height": 2000,
    "avif": true,
    "webp": true
  },
  "/assets/images/welcome/welcome-background.png": {
    "width": 2000,
    "height": 1329,
    "avif": true,
    "webp": true
  }
};
