/**
 * AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
 * Maps each image's web path to its intrinsic size and which modern formats
 * exist, so <Picture> can set width/height (CLS) and emit only the <source>s
 * whose sibling file was actually generated.
 */
export const imageManifest: Record<string, { width: number; height: number; avif?: boolean; webp?: boolean }> = {
  "/assets/images/0WtTlUnGSMQLo0YDGvoTdjyhMEc.png": {
    "width": 768,
    "height": 458
  },
  "/assets/images/1MilzwluR4WPySgY1Nc71NA7z10.jpg": {
    "width": 2000,
    "height": 2000,
    "avif": true,
    "webp": true
  },
  "/assets/images/24WMO9KZT30jBPFpwrgWt8rkSs.jpg": {
    "width": 2000,
    "height": 1331,
    "avif": true,
    "webp": true
  },
  "/assets/images/29nftr9xwtYw2wzRwUXbsYBA8Lw.png": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/2OyxeqKFVJBlpaZYbucB087OteU.png": {
    "width": 1570,
    "height": 391
  },
  "/assets/images/2o7PKySlJfnTfrnUJMjqKSpqHA.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/3icxBJ1CcHn6M34eovnFgccTZR0.jpg": {
    "width": 2000,
    "height": 1331,
    "avif": true,
    "webp": true
  },
  "/assets/images/44iQIZPqRkD7728oDk6fVdVgQ.png": {
    "width": 1040,
    "height": 838
  },
  "/assets/images/8JSXibl4A4aZTwJgXOWiMm5Yio.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/8y7OL16jlkcxqLPypsoox88cM8.jpg": {
    "width": 2000,
    "height": 1462,
    "avif": true,
    "webp": true
  },
  "/assets/images/9yaN44IumqxW2zGrUItm4iU18.png": {
    "width": 512,
    "height": 512,
    "avif": true,
    "webp": true
  },
  "/assets/images/C7lvJXp3dybbCUCltGehqzDyw4.png": {
    "width": 1310,
    "height": 1390
  },
  "/assets/images/CPPiPrmwNlBDD16ZjEsEp7jSOYQ.png": {
    "width": 512,
    "height": 512,
    "avif": true,
    "webp": true
  },
  "/assets/images/FS3ISXEUHf4xNgOzHz1v79bPNPo.jpg": {
    "width": 2000,
    "height": 1331,
    "avif": true,
    "webp": true
  },
  "/assets/images/FeaVRWV08CQHZHnzXhBakRt95o.jpg": {
    "width": 2000,
    "height": 2000,
    "avif": true,
    "webp": true
  },
  "/assets/images/Kb9qe3sHcAJx3Q5JAgWzIINlkI.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/LB31XkKlru3wRHoN0ROFW1Y1BE.jpeg": {
    "width": 864,
    "height": 540,
    "avif": true,
    "webp": true
  },
  "/assets/images/O46nYIHhimV9ETWDlqrcx971ZiM.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/Q7FknPV2hRB0NaQJVTxDxhqy1ok.png": {
    "width": 2000,
    "height": 1600
  },
  "/assets/images/QbK87ttZH4QcYXv2gmEfA19gJM.jpeg": {
    "width": 461,
    "height": 461,
    "avif": true,
    "webp": true
  },
  "/assets/images/QsZVf7HgM2bFcnXMjnoZj9lfudY.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/U5a4MBIv6ReTsrawoDNaPwK7cbc.png": {
    "width": 422,
    "height": 630,
    "avif": true,
    "webp": true
  },
  "/assets/images/VQm4I4LuWNHC0UemB1sslF3p8.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/X4BtJgPPmF3pmQX6HxtFctIg.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/ZxVXYgfcXSA9Icu75YPXMpFKm2Y.png": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/afjyIBAmXZ8DGW3gvaIVbNIIoU.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/amb-equipe.jpg": {
    "width": 1600,
    "height": 1064,
    "avif": true,
    "webp": true
  },
  "/assets/images/amb-equipe-thumb.jpg": {
    "width": 500,
    "height": 333,
    "avif": true,
    "webp": true
  },
  "/assets/images/amb-foule.jpg": {
    "width": 1600,
    "height": 1064,
    "avif": true,
    "webp": true
  },
  "/assets/images/amb-foule-thumb.jpg": {
    "width": 500,
    "height": 333,
    "avif": true,
    "webp": true
  },
  "/assets/images/amb-oratrice.jpg": {
    "width": 1600,
    "height": 1064,
    "avif": true,
    "webp": true
  },
  "/assets/images/amb-oratrice-thumb.jpg": {
    "width": 500,
    "height": 333,
    "avif": true,
    "webp": true
  },
  "/assets/images/amb-pitch.jpg": {
    "width": 1600,
    "height": 1064,
    "avif": true,
    "webp": true
  },
  "/assets/images/amb-pitch-thumb.jpg": {
    "width": 500,
    "height": 333,
    "avif": true,
    "webp": true
  },
  "/assets/images/brand/logo-startup-weekend-nantes.png": {
    "width": 1024,
    "height": 330
  },
  "/assets/images/cCa01Jr6KZUDGU8OkU8loM1z0.jpg": {
    "width": 2000,
    "height": 1331,
    "avif": true,
    "webp": true
  },
  "/assets/images/cQsYNI5NzBkgWVy7WotaBRZ21X8.jpg": {
    "width": 2000,
    "height": 1483,
    "avif": true,
    "webp": true
  },
  "/assets/images/cjfdmDrvGd9wKFVkjxVAYft8Yg.png": {
    "width": 1080,
    "height": 1080,
    "avif": true,
    "webp": true
  },
  "/assets/images/cq8ZzypnQ3B7cnq3vSe9YqtKZkc.jpeg": {
    "width": 515,
    "height": 540,
    "avif": true,
    "webp": true
  },
  "/assets/images/eRSRmPp4xOQQD6xgxPzGxkwZ4.png": {
    "width": 512,
    "height": 512,
    "avif": true,
    "webp": true
  },
  "/assets/images/f4AyPqq1hjMZxQxCR0mkLhZ7Q.png": {
    "width": 1080,
    "height": 855
  },
  "/assets/images/hEoUoeabKge2WBaQJP62xwnrEEQ.png": {
    "width": 1080,
    "height": 1080
  },
  "/assets/images/hXxw44XRfD7QExm9wAo9ESWFyI.jpeg": {
    "width": 452,
    "height": 452,
    "avif": true,
    "webp": true
  },
  "/assets/images/hero/hero-background.png": {
    "width": 1659,
    "height": 1361,
    "avif": true
  },
  "/assets/images/hero/hero-participants.png": {
    "width": 1440,
    "height": 1179
  },
  "/assets/images/hnQXqgk32dqlRBwcUizHzN1Q.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/intro/event-pitch-speaker.jpg": {
    "width": 2000,
    "height": 1331,
    "avif": true,
    "webp": true
  },
  "/assets/images/intro/intro-group-photo.jpg": {
    "width": 2000,
    "height": 1331,
    "avif": true,
    "webp": true
  },
  "/assets/images/intro/intro-team-brainstorming.jpg": {
    "width": 2000,
    "height": 1331,
    "avif": true,
    "webp": true
  },
  "/assets/images/intro/intro-tshirt-bad-ideas-good-stories.jpg": {
    "width": 2000,
    "height": 1331,
    "avif": true,
    "webp": true
  },
  "/assets/images/itdvMnDtbQRtWeHHjc1JZFdBDhM.png": {
    "width": 1024,
    "height": 330
  },
  "/assets/images/kprcfjkwgOzbgcID4jUNV5YNis.png": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/lyIwOv1puBWIqCuDn2zoYOXI9BY.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/mowMp6Vf0kSPXZHQB9N5E.png": {
    "width": 1080,
    "height": 1080
  },
  "/assets/images/njJ5WEX0VG3pn7hDzt3SU9AGg.png": {
    "width": 2000,
    "height": 1329,
    "avif": true,
    "webp": true
  },
  "/assets/images/oRq8HnnCP8CkxrvFeQvMp4tBA.png": {
    "width": 1440,
    "height": 1179
  },
  "/assets/images/orga/ana-pascaud.png": {
    "width": 1280,
    "height": 1707,
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/clara-garnier.png": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/florence-poyvre.png": {
    "width": 512,
    "height": 512,
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/gregory-thibord.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/guillaume-parthenay.png": {
    "width": 512,
    "height": 512,
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/louis-ammonique.png": {
    "width": 1080,
    "height": 1080,
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/robin-goutard.png": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/romain-perraut.png": {
    "width": 512,
    "height": 512,
    "avif": true,
    "webp": true
  },
  "/assets/images/palace-1.jpg": {
    "width": 1600,
    "height": 1064,
    "avif": true,
    "webp": true
  },
  "/assets/images/palace-2.jpg": {
    "width": 1600,
    "height": 1064,
    "avif": true,
    "webp": true
  },
  "/assets/images/palace-3.jpg": {
    "width": 1600,
    "height": 1064,
    "avif": true,
    "webp": true
  },
  "/assets/images/palace-4.jpg": {
    "width": 1600,
    "height": 1064,
    "avif": true,
    "webp": true
  },
  "/assets/images/palace-5.jpg": {
    "width": 1600,
    "height": 1064,
    "avif": true,
    "webp": true
  },
  "/assets/images/palace-6.jpg": {
    "width": 1600,
    "height": 1064,
    "avif": true,
    "webp": true
  },
  "/assets/images/palace-pano.jpg": {
    "width": 2000,
    "height": 1506,
    "avif": true,
    "webp": true
  },
  "/assets/images/sfniMLAtv98tHDMYDkETbcpvfak.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/benjamin-communier.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/benjamin-guillet.png": {
    "width": 422,
    "height": 630,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/claire-bretton.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/eric-lebrette.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/florian-herveou.jpeg": {
    "width": 584,
    "height": 584,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/johan-ricaut.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/lucie-valette.jpeg": {
    "width": 461,
    "height": 461,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/mathilde-bermond.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/nicolas-laurent.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/pauline-corriou.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/samuel-berthe.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/simon-timssale.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/thomas-matthieu.jpeg": {
    "width": 452,
    "height": 452,
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/vincent-roux.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/sponsors/sponsor-allovoisins.png": {
    "width": 1080,
    "height": 1080
  },
  "/assets/images/sponsors/sponsor-arzel.png": {
    "width": 768,
    "height": 458
  },
  "/assets/images/sponsors/sponsor-clever-cloud.png": {
    "width": 1310,
    "height": 1390
  },
  "/assets/images/sponsors/sponsor-crisp.png": {
    "width": 2000,
    "height": 499
  },
  "/assets/images/sponsors/sponsor-finalli.png": {
    "width": 2000,
    "height": 1600
  },
  "/assets/images/sponsors/sponsor-guest-suite.png": {
    "width": 1080,
    "height": 855
  },
  "/assets/images/sponsors/sponsor-icilundi.png": {
    "width": 512,
    "height": 312
  },
  "/assets/images/sponsors/sponsor-kiliogene.png": {
    "width": 1570,
    "height": 391
  },
  "/assets/images/sponsors/sponsor-nantes-metropole.png": {
    "width": 1080,
    "height": 1080
  },
  "/assets/images/sponsors/sponsor-pepite-pays-de-la-loire.png": {
    "width": 402,
    "height": 385
  },
  "/assets/images/sponsors/sponsor-reseau-entreprendre-atlantique.png": {
    "width": 1040,
    "height": 838
  },
  "/assets/images/vDdpuf0bvfUg1jOKqSriwoI8As.jpeg": {
    "width": 584,
    "height": 584,
    "avif": true,
    "webp": true
  },
  "/assets/images/venue/venue-palace-1.jpeg": {
    "width": 515,
    "height": 540,
    "avif": true,
    "webp": true
  },
  "/assets/images/venue/venue-palace-2.jpg": {
    "width": 2000,
    "height": 2000,
    "avif": true,
    "webp": true
  },
  "/assets/images/venue/venue-palace-3.jpeg": {
    "width": 864,
    "height": 540,
    "avif": true,
    "webp": true
  },
  "/assets/images/venue/venue-palace-4.jpg": {
    "width": 2000,
    "height": 1462,
    "avif": true,
    "webp": true
  },
  "/assets/images/venue/venue-palace-5.jpg": {
    "width": 2000,
    "height": 1483,
    "avif": true,
    "webp": true
  },
  "/assets/images/venue/venue-palace-panoramic.jpg": {
    "width": 2000,
    "height": 2000,
    "avif": true,
    "webp": true
  },
  "/assets/images/vidXeHjc3C1LSKcrMy2PAH2oxCQ.jpeg": {
    "width": 800,
    "height": 800,
    "avif": true,
    "webp": true
  },
  "/assets/images/wMWsWm7njm6vmBfMVwkVaW4.png": {
    "width": 1659,
    "height": 1361,
    "avif": true
  },
  "/assets/images/welcome/welcome-background.png": {
    "width": 2000,
    "height": 1329,
    "avif": true,
    "webp": true
  },
  "/assets/images/xbrzvOd572A3buGabxbYYWHMDTA.png": {
    "width": 512,
    "height": 312
  },
  "/assets/images/xgqZP9NFB8rOgqvLhHUkyDYRJYU.png": {
    "width": 2000,
    "height": 499
  },
  "/assets/images/zql7stHN2Rthx6uOdsagCNhv2M.png": {
    "width": 402,
    "height": 385
  },
  "/assets/images/zrnozkkMGZmZ62YKvXWpLSdBMfE.png": {
    "width": 1280,
    "height": 1707,
    "avif": true,
    "webp": true
  }
};
