import './RisoIllu.css';

type Subject = 'briefing' | 'console' | 'rocket' | 'moon';

/** Intrinsic pixel size of each riso-*.webp source (same for both surface variants, ±1px) — see public/assets/images/illus-riso/. */
const INTRINSIC_SIZE: Record<Subject, { width: number; height: number }> = {
  briefing: { width: 1000, height: 965 },
  console: { width: 1000, height: 837 },
  rocket: { width: 1000, height: 970 },
  moon: { width: 1000, height: 993 },
};

/**
 * `-thumb` variants for the subject/surface combos actually rendered small
 * (moon in Intro's collage, console in Contact's medallion — both cap out well
 * under 300px on screen). PageSpeed flagged the full 1000px source as 5-8x
 * oversized there. Generated once at the display-appropriate width with the
 * same sharp settings as scripts/optimize-images.mjs; not auto-generated by
 * that script since illus-riso/ ships hand-authored .webp, not raster photos.
 * Any subject/surface combo without an entry here falls back to the full-size
 * source (e.g. Hero's briefing-on-dark, which needs up to 460px).
 */
const THUMB: Partial<Record<`${Subject}-${'dark' | 'light'}`, { width: number; height: number }>> =
  {
    'moon-light': { width: 400, height: 397 },
    'console-dark': { width: 550, height: 460 },
  };

type Props = {
  /** Sujet de l'illustration riso. */
  subject: Subject;
  /** Surface sur laquelle elle est posée — choisit la variante de couleur qui contraste. */
  surface: 'dark' | 'light';
  alt: string;
  /** Halo radial derrière l'illu. */
  glow?: 'bleu' | 'jaune' | 'none';
  /** Masque l'illu dans un médaillon circulaire (hublot de mission). */
  round?: boolean;
  className?: string;
  eager?: boolean;
};

export default function RisoIllu({
  subject,
  surface,
  alt,
  glow = 'bleu',
  round = false,
  className = '',
  eager = false,
}: Props) {
  const thumb = THUMB[`${subject}-${surface}`];
  const size = thumb ?? INTRINSIC_SIZE[subject];
  const suffix = thumb ? '-thumb' : '';

  return (
    <figure
      className={`riso ${className}`}
      data-surface={surface}
      data-glow={glow}
      data-round={round ? 'true' : undefined}
    >
      <span className="riso-glow" aria-hidden="true" />
      <img
        src={`/assets/images/illus-riso/riso-${subject}-on-${surface}${suffix}.webp`}
        alt={alt}
        className="riso-img"
        loading={eager ? 'eager' : 'lazy'}
        decoding="async"
        width={size.width}
        height={size.height}
      />
    </figure>
  );
}
