/**
 * AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
 * Maps each image's web path to which modern formats exist, so <Picture>
 * emits only the <source>s whose sibling file was actually generated.
 */
export const imageManifest: Record<string, { avif?: boolean; webp?: boolean }> = {
  "/assets/images/brand/logo-startup-weekend-nantes.png": {},
  "/assets/images/hero/hero-background.png": {
    "avif": true
  },
  "/assets/images/hero/hero-participants.png": {},
  "/assets/images/intro/event-pitch-speaker.jpg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/intro/intro-group-photo.jpg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/intro/intro-team-brainstorming.jpg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/intro/intro-tshirt-bad-ideas-good-stories.jpg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/ana-pascaud.png": {
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/clara-garnier.png": {
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/florence-poyvre.png": {
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/gregory-thibord.jpeg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/guillaume-parthenay.png": {
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/louis-ammonique.png": {
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/robin-goutard.png": {
    "avif": true,
    "webp": true
  },
  "/assets/images/orga/romain-perraut.png": {
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/benjamin-communier.jpeg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/benjamin-guillet.png": {
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/claire-bretton.jpeg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/eric-lebrette.jpeg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/florian-herveou.jpeg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/johan-ricaut.jpeg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/lucie-valette.jpeg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/mathilde-bermond.jpeg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/nicolas-laurent.jpeg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/pauline-corriou.jpeg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/samuel-berthe.jpeg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/simon-timssale.jpeg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/thomas-matthieu.jpeg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/speakers/vincent-roux.jpeg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/sponsors/sponsor-allovoisins.png": {
    "avif": true
  },
  "/assets/images/sponsors/sponsor-arzel.png": {},
  "/assets/images/sponsors/sponsor-clever-cloud.png": {},
  "/assets/images/sponsors/sponsor-crisp.png": {},
  "/assets/images/sponsors/sponsor-finalli.png": {},
  "/assets/images/sponsors/sponsor-guest-suite.png": {},
  "/assets/images/sponsors/sponsor-icilundi.png": {},
  "/assets/images/sponsors/sponsor-kiliogene.png": {},
  "/assets/images/sponsors/sponsor-nantes-metropole.png": {},
  "/assets/images/sponsors/sponsor-pepite-pays-de-la-loire.png": {},
  "/assets/images/sponsors/sponsor-reseau-entreprendre-atlantique.png": {},
  "/assets/images/venue/venue-palace-1.jpeg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/venue/venue-palace-2.jpg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/venue/venue-palace-3.jpeg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/venue/venue-palace-4.jpg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/venue/venue-palace-5.jpg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/venue/venue-palace-panoramic.jpg": {
    "avif": true,
    "webp": true
  },
  "/assets/images/welcome/welcome-background.png": {
    "avif": true,
    "webp": true
  }
};
